[package]
authors = ["Icelle Ku <icelleku@gmail.com>"]
name = "quandl"
version = "0.1.0"
keywords = ["quandl"]
license = "MIT/Apache-2.0"

[dependencies]
chrono = "0.2.17"
curl = "0.2.14"
hyper = "0.7.0"
quick-error = "0.1.4"
serde_json = "0.6.0"
url = "0.5.0"

[dependencies.clippy]
optional = true
version = "0.0.29"

[features]
default = []
# used to run test cases that call out to the quandl API directly
test-quandl-api = []
